project:
  type: website
  output-dir: docs

website:
  title: "Jed Lichtensztajn"

  navbar:
    pinnedd: true


  #sub pages
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: CV/CV.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

